Repository JECT-Study/Chzz-Market-Backend, pull requests merged in 2024-09, with the labels that each got.

#26 feat: auction history inquire
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/dto/response/AuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/entity/Auction.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustom.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/image/entity/Image.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/resources/db/data.sql
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImplTest.java
Labels: ✨feature, 👨🏻‍💻backend

#32 refactor: 나의 경매목록 조회 기능 url 변경으로 인한 리팩토링
  src/main/java/org/chzz/market/common/config/PageResponseSerializer.java
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/dto/response/UserAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustom.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/user/controller/MyController.java
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImplTest.java
Labels: 👨🏻‍💻backend, 🪄refactor

#30 feat: best auction inquire
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustom.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImplTest.java
Labels: ✨feature, 👨🏻‍💻backend

#28 feat: 유저 프로필 수정 기능 구현
  src/main/java/org/chzz/market/domain/product/service/ProductService.java
  src/main/java/org/chzz/market/domain/user/controller/MyController.java
  src/main/java/org/chzz/market/domain/user/controller/UserController.java
  src/main/java/org/chzz/market/domain/user/dto/UpdateProfileResponse.java
  src/main/java/org/chzz/market/domain/user/dto/UpdateUserProfileRequest.java
  src/main/java/org/chzz/market/domain/user/entity/User.java
  src/main/java/org/chzz/market/domain/user/error/UserErrorCode.java
  src/main/java/org/chzz/market/domain/user/repository/UserRepository.java
  src/main/java/org/chzz/market/domain/user/service/UserService.java
  src/test/java/org/chzz/market/domain/user/service/UserServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#33 feat: 알림함 기능 구현
  src/main/java/org/chzz/market/common/config/AsyncConfig.java
  src/main/java/org/chzz/market/common/error/handler/ExceptionHandlingFilter.java
  src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/notification/controller/NotificationController.java
  src/main/java/org/chzz/market/domain/notification/dto/NotificationMessage.java
  src/main/java/org/chzz/market/domain/notification/dto/NotificationRealMessage.java
  src/main/java/org/chzz/market/domain/notification/dto/response/NotificationResponse.java
  src/main/java/org/chzz/market/domain/notification/dto/response/NotificationSseResponse.java
  src/main/java/org/chzz/market/domain/notification/entity/Notification.java
  src/main/java/org/chzz/market/domain/notification/entity/NotificationType.java
  src/main/java/org/chzz/market/domain/notification/error/NotificationErrorCode.java
  src/main/java/org/chzz/market/domain/notification/event/NotificationEvent.java
  src/main/java/org/chzz/market/domain/notification/event/NotificationEventListener.java
  src/main/java/org/chzz/market/domain/notification/repository/NotificationRepository.java
  src/main/java/org/chzz/market/domain/notification/repository/NotificationRepositoryCustom.java
  src/main/java/org/chzz/market/domain/notification/repository/NotificationRepositoryImpl.java
  src/main/java/org/chzz/market/domain/notification/service/NotificationService.java
  src/main/java/org/chzz/market/domain/notification/service/RedisPublisher.java
  src/main/java/org/chzz/market/domain/notification/service/RedisSubscriber.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/java/org/chzz/market/domain/product/service/ProductService.java
  src/main/java/org/chzz/market/domain/user/controller/MyController.java
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImplTest.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
  src/test/java/org/chzz/market/domain/notification/repository/NotificationRepositoryImplTest.java
  src/test/java/org/chzz/market/domain/notification/service/NotificationServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend, 🗂️db

#34 feat: 경매의 입찰 내역 조회
  src/main/java/org/chzz/market/common/dto/PageResponse.java
  src/main/java/org/chzz/market/common/error/ErrorResponse.java
  src/main/java/org/chzz/market/common/error/GlobalErrorCode.java
  src/main/java/org/chzz/market/common/error/handler/GlobalExceptionHandler.java
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/entity/Auction.java
  src/main/java/org/chzz/market/domain/auction/error/AuctionErrorCode.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/bid/controller/BidController.java
  src/main/java/org/chzz/market/domain/bid/dto/response/BidInfoResponse.java
  src/main/java/org/chzz/market/domain/bid/entity/Bid.java
  src/main/java/org/chzz/market/domain/bid/repository/BidRepositoryCustom.java
  src/main/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/bid/service/BidService.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/java/org/chzz/market/domain/product/error/ProductErrorCode.java
  src/test/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/bid/service/BidServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#31 feat: 유저 프로필 조회 기능 구현
  src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
  src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/RegisterAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/StartAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/UserAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/entity/Auction.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustom.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionRegistrationServiceFactory.java
  src/main/java/org/chzz/market/domain/auction/service/register/AuctionRegisterService.java
  src/main/java/org/chzz/market/domain/auction/type/AuctionRegisterType.java
  src/main/java/org/chzz/market/domain/auction/type/AuctionStatus.java
  src/main/java/org/chzz/market/domain/user/controller/UserController.java
  src/main/java/org/chzz/market/domain/user/dto/response/KaKaoResponse.java
  src/main/java/org/chzz/market/domain/user/dto/response/NaverResponse.java
  src/main/java/org/chzz/market/domain/user/dto/response/OAuth2Response.java
  src/main/java/org/chzz/market/domain/user/dto/response/ParticipationCountsResponse.java
  src/main/java/org/chzz/market/domain/user/dto/response/UserProfileResponse.java
  src/main/java/org/chzz/market/domain/user/entity/User.java
  src/main/java/org/chzz/market/domain/user/repository/UserRepository.java
  src/main/java/org/chzz/market/domain/user/service/CustomOAuth2UserService.java
  src/main/java/org/chzz/market/domain/user/service/UserService.java
  src/test/java/org/chzz/market/domain/auction/controller/AuctionControllerTest.java
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImplTest.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
  src/test/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/bid/service/BidServiceTest.java
  src/test/java/org/chzz/market/domain/user/service/UserServiceTest.java
  src/test/java/org/chzz/market/util/AuctionTestFactory.java
Labels: ✨feature, 👨🏻‍💻backend

#37 feat: 나의 상품 조회 기능 구현
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/dto/response/LostAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/WonAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustom.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/bid/entity/Bid.java
  src/main/java/org/chzz/market/domain/product/controller/ProductController.java
  src/main/java/org/chzz/market/domain/product/dto/BaseProductDTO.java
  src/main/java/org/chzz/market/domain/product/dto/ProductResponse.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/org/chzz/market/domain/product/service/ProductService.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
  src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend

#35 feat: imminent auction inquire
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustom.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/resources/db/data.sql
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImplTest.java
Labels: ✨feature, 👨🏻‍💻backend

#48 chore: flyway setting
  build.gradle
  src/main/resources/application-test.yml
  src/main/resources/db/migration/V1__init.sql
Labels: ⚙️chore, 👨🏻‍💻backend

#44 feat: member address management
  src/main/java/org/chzz/market/common/config/logging/P6spyLogMessageFormatConfiguration.java
  src/main/java/org/chzz/market/common/error/GlobalErrorCode.java
  src/main/java/org/chzz/market/common/error/handler/GlobalExceptionHandler.java
  src/main/java/org/chzz/market/domain/address/controller/AddressController.java
  src/main/java/org/chzz/market/domain/address/dto/request/AddressDto.java
  src/main/java/org/chzz/market/domain/address/entity/Address.java
  src/main/java/org/chzz/market/domain/address/repository/AddressRepository.java
  src/main/java/org/chzz/market/domain/address/service/AddressService.java
  src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/user/controller/UserController.java
  src/main/java/org/chzz/market/domain/user/entity/User.java
  src/main/java/org/chzz/market/domain/user/oauth2/CustomFailureHandler.java
  src/main/java/org/chzz/market/domain/user/service/UserService.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend, 🗂️db

#42 refactor: 알림 Entity 구조 변경
  .github/PULL_REQUEST_TEMPLATE.md
  compose-local.yaml
  nginx.conf
  src/main/java/org/chzz/market/common/config/SecurityConfig.java
  src/main/java/org/chzz/market/common/error/handler/ExceptionHandlingFilter.java
  src/main/java/org/chzz/market/common/filter/JWTFilter.java
  src/main/java/org/chzz/market/common/filter/NotFoundFilter.java
  src/main/java/org/chzz/market/common/util/CookieUtil.java
  src/main/java/org/chzz/market/common/validation/annotation/EnumValue.java
  src/main/java/org/chzz/market/common/validation/validator/EnumValidator.java
  src/main/java/org/chzz/market/common/validation/validator/ThousandMultipleValidator.java
  src/main/java/org/chzz/market/domain/auction/error/AuctionErrorCode.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/bank_account/entity/BankAccount.java
  src/main/java/org/chzz/market/domain/bid/controller/BidController.java
  src/main/java/org/chzz/market/domain/bid/dto/BidCreateRequest.java
  src/main/java/org/chzz/market/domain/notification/controller/NotificationController.java
  src/main/java/org/chzz/market/domain/notification/dto/NotificationRealMessage.java
  src/main/java/org/chzz/market/domain/notification/dto/response/NotificationResponse.java
  src/main/java/org/chzz/market/domain/notification/dto/response/NotificationSseResponse.java
  src/main/java/org/chzz/market/domain/notification/entity/AuctionFailureNotification.java
  src/main/java/org/chzz/market/domain/notification/entity/AuctionNonWinnerNotification.java
  src/main/java/org/chzz/market/domain/notification/entity/AuctionStartNotification.java
  src/main/java/org/chzz/market/domain/notification/entity/AuctionSuccessNotification.java
  src/main/java/org/chzz/market/domain/notification/entity/AuctionWinnerNotification.java
  src/main/java/org/chzz/market/domain/notification/entity/Notification.java
  src/main/java/org/chzz/market/domain/notification/entity/NotificationType.java
  src/main/java/org/chzz/market/domain/notification/entity/PreAuctionCanceledNotification.java
  src/main/java/org/chzz/market/domain/notification/event/NotificationEvent.java
  src/main/java/org/chzz/market/domain/notification/event/NotificationEventListener.java
  src/main/java/org/chzz/market/domain/notification/repository/NotificationRepositoryImpl.java
  src/main/java/org/chzz/market/domain/notification/service/NotificationService.java
  src/main/java/org/chzz/market/domain/notification/service/RedisSubscriber.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/java/org/chzz/market/domain/product/service/ProductService.java
  src/main/java/org/chzz/market/domain/token/entity/TokenType.java
  src/main/java/org/chzz/market/domain/user/controller/UserController.java
  src/main/java/org/chzz/market/domain/user/dto/request/UserCreateRequest.java
  src/main/java/org/chzz/market/domain/user/entity/User.java
  src/main/java/org/chzz/market/domain/user/error/UserErrorCode.java
  src/main/java/org/chzz/market/domain/user/oauth2/CustomSuccessHandler.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
  src/test/java/org/chzz/market/domain/notification/repository/NotificationRepositoryImplTest.java
  src/test/java/org/chzz/market/domain/notification/service/NotificationServiceTest.java
  src/test/java/org/chzz/market/domain/user/service/UserServiceTest.java
Labels: 👨🏻‍💻backend, 🪄refactor

#49 chore: monitoring setting
  compose-local.yaml
  monitoring/loki/loki-config.yaml
  monitoring/prometheus/prometheus.yml
  src/main/java/org/chzz/market/common/config/SecurityConfig.java
Labels: ⚙️chore, 👨🏻‍💻backend

#54 chore: deploy action setting 수정
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deployment-config.yml
  .github/workflows/pr-title-and-branch-validation.yml
  .github/workflows/release-drafter-config.yml
  .github/workflows/release-tag.yml
  nginx.conf
  src/main/java/org/chzz/market/common/config/logging/P6spyLogMessageFormatConfiguration.java
Labels: ⚙️chore

#55 move: release-drafter-config.yml 파일 위치 변경
  .github/release-drafter-config.yml
  .github/workflows/pr-title-and-branch-validation.yml
Labels: ⚙️chore

#58 chore: nginx 업로드 용량 제한 설정
  .github/workflows/release-tag.yml
  compose-local.yaml
  nginx.conf
  src/main/resources/db/migration/V1__init.sql
Labels: ⚙️chore
