Repository JECT-Study/Chzz-Market-Backend, pull requests merged in 2024-08, with the labels that each got.

#9 feat: 경매 등록 기능 구현
  .github/workflows/intergration-config.yml
  build.gradle
  src/main/java/org/chzz/market/common/config/AWSConfig.java
  src/main/java/org/chzz/market/common/config/AuditingConfig.java
  src/main/java/org/chzz/market/common/config/QuerydslConfig.java
  src/main/java/org/chzz/market/common/config/RetryConfig.java
  src/main/java/org/chzz/market/common/config/SecurityConfig.java
  src/main/java/org/chzz/market/common/config/WebClientConfig.java
  src/main/java/org/chzz/market/common/config/WebConfig.java
  src/main/java/org/chzz/market/common/error/ErrorCode.java
  src/main/java/org/chzz/market/common/error/GlobalErrorCode.java
  src/main/java/org/chzz/market/common/error/exception/BusinessException.java
  src/main/java/org/chzz/market/common/error/handler/GlobalExceptionHandler.java
  src/main/java/org/chzz/market/common/error/response/ErrorResponse.java
  src/main/java/org/chzz/market/common/validation/annotation/ThousandMultiple.java
  src/main/java/org/chzz/market/common/validation/validator/ThousandMultipleValidator.java
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/dto/AuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/request/AuctionCreateRequest.java
  src/main/java/org/chzz/market/domain/auction/entity/Auction.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/image/entity/Image.java
  src/main/java/org/chzz/market/domain/image/error/ImageErrorCode.java
  src/main/java/org/chzz/market/domain/image/error/exception/ImageException.java
  src/main/java/org/chzz/market/domain/image/service/ImageService.java
  src/main/java/org/chzz/market/domain/image/service/ImageUploader.java
  src/main/java/org/chzz/market/domain/image/service/S3ImageUploader.java
  src/main/java/org/chzz/market/domain/payment/error/PaymentErrorCode.java
  src/main/java/org/chzz/market/domain/payment/error/PaymentException.java
  src/main/java/org/chzz/market/domain/payment/error/TossPaymentErrorCode.java
  src/main/java/org/chzz/market/domain/payment/error/TossPaymentException.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/java/org/chzz/market/domain/user/entity/User.java
  src/main/java/org/chzz/market/domain/user/error/UserException.java
  src/main/java/org/chzz/market/domain/user/error/exception/UserErrorCode.java
  src/main/resources/application-test.yml
  src/test/java/org/chzz/market/MarketApplicationTests.java
  src/test/java/org/chzz/market/common/AWSConfig.java
  src/test/java/org/chzz/market/common/DatabaseTest.java
  src/test/java/org/chzz/market/domain/auction/controller/AuctionControllerTest.java
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImplTest.java
Labels: ⚙️chore, ✨feature, 👨🏻‍💻backend

#11 chore: set deploy configuration
  .github/workflows/deployment-config.yml
  .gitignore
  Dockerfile
  build.gradle
  compose.yaml
  src/main/java/org/chzz/market/common/config/SecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
Labels: ⚙️chore, 👨🏻‍💻backend, 💻server

#19 feat: 입찰 기록 조회
  build.gradle
  src/main/java/org/chzz/market/common/config/CustomPageableHandlerMethodArgumentResolver.java
  src/main/java/org/chzz/market/common/config/JacksonConfig.java
  src/main/java/org/chzz/market/common/config/PageResponseSerializer.java
  src/main/java/org/chzz/market/common/config/QuerydslOrderConfig.java
  src/main/java/org/chzz/market/common/config/SecurityConfig.java
  src/main/java/org/chzz/market/common/config/WebConfig.java
  src/main/java/org/chzz/market/common/config/logging/P6spyLogMessageFormatConfiguration.java
  src/main/java/org/chzz/market/common/config/logging/P6spySqlFormatConfiguration.java
  src/main/java/org/chzz/market/common/dto/PageResponse.java
  src/main/java/org/chzz/market/common/error/GlobalErrorCode.java
  src/main/java/org/chzz/market/common/error/GlobalException.java
  src/main/java/org/chzz/market/common/error/handler/GlobalExceptionHandler.java
  src/main/java/org/chzz/market/common/util/OrderByNull.java
  src/main/java/org/chzz/market/common/util/QuerydslOrder.java
  src/main/java/org/chzz/market/common/util/QuerydslOrderProvider.java
  src/main/java/org/chzz/market/common/util/QuerydslOrderRegistry.java
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/dto/AuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/BaseAuctionDTO.java
  src/main/java/org/chzz/market/domain/auction/entity/Auction.java
  src/main/java/org/chzz/market/domain/auction/entity/SortType.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustom.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/bid/controller/BidController.java
  src/main/java/org/chzz/market/domain/bid/dto/query/BiddingRecord.java
  src/main/java/org/chzz/market/domain/bid/entity/Bid.java
  src/main/java/org/chzz/market/domain/bid/error/BidErrorCode.java
  src/main/java/org/chzz/market/domain/bid/repository/BidRepository.java
  src/main/java/org/chzz/market/domain/bid/repository/BidRepositoryCustom.java
  src/main/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/bid/service/BidService.java
  src/main/java/org/chzz/market/domain/payment/error/TossPaymentException.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/main/resources/db/data.sql
  src/test/java/org/chzz/market/common/DatabaseTest.java
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImplTest.java
  src/test/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImplTest.java
Labels: ✨feature, 👨🏻‍💻backend, 🪄refactor

#17 feat: 알림 기능 구현
  .github/workflows/intergration-config.yml
  src/main/java/org/chzz/market/common/config/JacksonConfig.java
  src/main/java/org/chzz/market/common/config/PageResponseSerializer.java
  src/main/java/org/chzz/market/common/config/RedisConfig.java
  src/main/java/org/chzz/market/common/config/logging/P6spyLogMessageFormatConfiguration.java
  src/main/java/org/chzz/market/common/config/logging/P6spySqlFormatConfiguration.java
  src/main/java/org/chzz/market/domain/notification/controller/NotificationController.java
  src/main/java/org/chzz/market/domain/notification/dto/NotificationEvent.java
  src/main/java/org/chzz/market/domain/notification/dto/NotificationMessage.java
  src/main/java/org/chzz/market/domain/notification/entity/Notification.java
  src/main/java/org/chzz/market/domain/notification/error/NotificationErrorCode.java
  src/main/java/org/chzz/market/domain/notification/error/NotificationException.java
  src/main/java/org/chzz/market/domain/notification/repository/EmitterRepository.java
  src/main/java/org/chzz/market/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/org/chzz/market/domain/notification/repository/NotificationRepository.java
  src/main/java/org/chzz/market/domain/notification/service/NotificationEventListener.java
  src/main/java/org/chzz/market/domain/notification/service/NotificationService.java
  src/main/java/org/chzz/market/domain/notification/service/RedisPublisher.java
  src/main/java/org/chzz/market/domain/notification/service/RedisSubscriber.java
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
Labels: ✨feature, 👨🏻‍💻backend, 🗂️db

#21 feat: 입찰 취소 구현
  src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
  src/main/java/org/chzz/market/domain/auction/entity/Auction.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImpl.java
  src/main/java/org/chzz/market/domain/bid/controller/BidController.java
  src/main/java/org/chzz/market/domain/bid/dto/BidCreateRequest.java
  src/main/java/org/chzz/market/domain/bid/entity/Bid.java
  src/main/java/org/chzz/market/domain/bid/error/BidErrorCode.java
  src/main/java/org/chzz/market/domain/bid/service/BidService.java
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImplTest.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
  src/test/java/org/chzz/market/domain/bid/service/BidServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend, 🗂️db

#20 feat: 상품 등록(사전 등록, 경매 등록, 사전->경매 전환) 구현
  src/main/java/org/chzz/market/common/config/SecurityConfig.java
  src/main/java/org/chzz/market/common/error/GlobalErrorCode.java
  src/main/java/org/chzz/market/common/error/exception/BusinessException.java
  src/main/java/org/chzz/market/common/error/handler/GlobalExceptionHandler.java
  src/main/java/org/chzz/market/common/error/response/ErrorResponse.java
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/dto/request/AuctionCreateRequest.java
  src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
  src/main/java/org/chzz/market/domain/auction/dto/request/PreRegisterRequest.java
  src/main/java/org/chzz/market/domain/auction/dto/request/RegisterAuctionRequest.java
  src/main/java/org/chzz/market/domain/auction/dto/request/StartAuctionRequest.java
  src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/MyAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/RegisterAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/StartAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/entity/Auction.java
  src/main/java/org/chzz/market/domain/auction/error/AuctionErrorCode.java
  src/main/java/org/chzz/market/domain/auction/error/AuctionException.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepository.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/auction/service/policy/AuctionPolicy.java
  src/main/java/org/chzz/market/domain/auction/service/policy/PreRegisterAuctionPolicy.java
  src/main/java/org/chzz/market/domain/auction/service/policy/RegisterAuctionPolicy.java
  src/main/java/org/chzz/market/domain/bid/error/BidException.java
  src/main/java/org/chzz/market/domain/bid/service/BidService.java
  src/main/java/org/chzz/market/domain/image/error/ImageErrorCode.java
  src/main/java/org/chzz/market/domain/image/error/exception/ImageException.java
  src/main/java/org/chzz/market/domain/image/service/ImageService.java
  src/main/java/org/chzz/market/domain/image/service/S3ImageUploader.java
  src/main/java/org/chzz/market/domain/notification/error/NotificationException.java
  src/main/java/org/chzz/market/domain/payment/error/PaymentException.java
  src/main/java/org/chzz/market/domain/payment/error/TossPaymentException.java
  src/main/java/org/chzz/market/domain/product/controller/ProductController.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/java/org/chzz/market/domain/product/error/ProductErrorCode.java
  src/main/java/org/chzz/market/domain/product/error/ProductException.java
  src/main/java/org/chzz/market/domain/user/controller/MyController.java
  src/main/java/org/chzz/market/domain/user/error/UserErrorCode.java
  src/main/java/org/chzz/market/domain/user/error/exception/UserException.java
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/main/resources/db/data.sql
  src/test/java/org/chzz/market/common/TestConfig.java
  src/test/java/org/chzz/market/domain/auction/controller/AuctionControllerTest.java
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImplTest.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
  src/test/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/bid/service/BidServiceTest.java
  src/test/java/org/chzz/market/util/AuctionTestFactory.java
  src/test/java/org/chzz/market/util/ProductTestFactory.java
  src/test/java/org/chzz/market/util/UserTestFactory.java
Labels: 👨🏻‍💻backend, 🪄refactor

#22 feat: 사전 등록 상품 수정 기능 구현
  src/main/java/org/chzz/market/common/config/SecurityConfig.java
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
  src/main/java/org/chzz/market/domain/auction/dto/request/PreRegisterRequest.java
  src/main/java/org/chzz/market/domain/auction/dto/request/RegisterAuctionRequest.java
  src/main/java/org/chzz/market/domain/auction/dto/request/StartAuctionRequest.java
  src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/PreRegisterResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/RegisterAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/RegisterResponse.java
  src/main/java/org/chzz/market/domain/auction/entity/Auction.java
  src/main/java/org/chzz/market/domain/auction/enums/AuctionRegisterType.java
  src/main/java/org/chzz/market/domain/auction/error/AuctionErrorCode.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionRegistrationServiceFactory.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/auction/service/policy/AuctionPolicy.java
  src/main/java/org/chzz/market/domain/auction/service/policy/PreRegisterAuctionPolicy.java
  src/main/java/org/chzz/market/domain/auction/service/policy/RegisterAuctionPolicy.java
  src/main/java/org/chzz/market/domain/auction/service/register/AuctionRegisterService.java
  src/main/java/org/chzz/market/domain/auction/service/register/AuctionRegistrationService.java
  src/main/java/org/chzz/market/domain/auction/service/register/PreRegisterService.java
  src/main/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/image/service/ImageService.java
  src/main/java/org/chzz/market/domain/product/controller/ProductController.java
  src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
  src/main/java/org/chzz/market/domain/product/dto/UpdateProductResponse.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/java/org/chzz/market/domain/product/error/ProductErrorCode.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepository.java
  src/main/java/org/chzz/market/domain/product/service/ProductService.java
  src/main/resources/application-local.yml
  src/test/java/org/chzz/market/domain/auction/controller/AuctionControllerTest.java
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImplTest.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
  src/test/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/bid/service/BidServiceTest.java
  src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java
  src/test/java/org/chzz/market/util/AuctionTestFactory.java
Labels: ✨feature, 👨🏻‍💻backend

#23 feat: 사전 등록 상품 삭제 기능 구현
  src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
  src/main/java/org/chzz/market/domain/auction/dto/request/PreRegisterRequest.java
  src/main/java/org/chzz/market/domain/auction/dto/request/RegisterAuctionRequest.java
  src/main/java/org/chzz/market/domain/auction/dto/request/StartAuctionRequest.java
  src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/RegisterAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/entity/Auction.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/product/controller/ProductController.java
  src/main/java/org/chzz/market/domain/product/dto/DeleteProductResponse.java
  src/main/java/org/chzz/market/domain/product/error/ProductErrorCode.java
  src/main/java/org/chzz/market/domain/product/service/ProductService.java
  src/test/java/org/chzz/market/domain/auction/controller/AuctionControllerTest.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
  src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java
  src/test/java/org/chzz/market/util/AuctionTestFactory.java
Labels: ✨feature, 👨🏻‍💻backend

#24 feat: 사전 등록 상품 조회 기능 구현
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/like/entity/Like.java
  src/main/java/org/chzz/market/domain/like/repository/LikeRepository.java
  src/main/java/org/chzz/market/domain/product/controller/ProductController.java
  src/main/java/org/chzz/market/domain/product/dto/BaseProductDTO.java
  src/main/java/org/chzz/market/domain/product/dto/CategoryResponse.java
  src/main/java/org/chzz/market/domain/product/dto/ProductDetailsResponse.java
  src/main/java/org/chzz/market/domain/product/dto/ProductResponse.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepository.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/org/chzz/market/domain/product/service/ProductService.java
  src/test/java/org/chzz/market/domain/auction/controller/AuctionControllerTest.java
  src/test/java/org/chzz/market/domain/product/repository/ProductRepositoryImplTest.java
  src/test/java/org/chzz/market/util/AuctionTestFactory.java
Labels: ✨feature, 👨🏻‍💻backend

#29 feat: 소셜로그인 및 JWT 토큰 발급
  build.gradle
  src/main/java/org/chzz/market/common/config/LoginUser.java
  src/main/java/org/chzz/market/common/config/LoginUserArgumentResolver.java
  src/main/java/org/chzz/market/common/config/SecurityConfig.java
  src/main/java/org/chzz/market/common/config/WebConfig.java
  src/main/java/org/chzz/market/common/error/GlobalErrorCode.java
  src/main/java/org/chzz/market/common/error/handler/CustomAccessDeniedHandler.java
  src/main/java/org/chzz/market/common/error/handler/CustomAuthenticationEntryPoint.java
  src/main/java/org/chzz/market/common/error/handler/ExceptionHandlingFilter.java
  src/main/java/org/chzz/market/common/filter/JWTFilter.java
  src/main/java/org/chzz/market/common/util/CookieUtil.java
  src/main/java/org/chzz/market/common/util/JWTUtil.java
  src/main/java/org/chzz/market/domain/bank_account/entity/BankAccount.java
  src/main/java/org/chzz/market/domain/token/dto/TokenData.java
  src/main/java/org/chzz/market/domain/token/entity/TokenType.java
  src/main/java/org/chzz/market/domain/token/error/TokenErrorCode.java
  src/main/java/org/chzz/market/domain/token/error/exception/TokenException.java
  src/main/java/org/chzz/market/domain/token/repository/RefreshTokenRepository.java
  src/main/java/org/chzz/market/domain/token/service/TokenService.java
  src/main/java/org/chzz/market/domain/user/controller/UserController.java
  src/main/java/org/chzz/market/domain/user/dto/CustomUserDetails.java
  src/main/java/org/chzz/market/domain/user/dto/KaKaoResponse.java
  src/main/java/org/chzz/market/domain/user/dto/NaverResponse.java
  src/main/java/org/chzz/market/domain/user/dto/OAuth2Response.java
  src/main/java/org/chzz/market/domain/user/dto/request/UserCreateRequest.java
  src/main/java/org/chzz/market/domain/user/dto/response/NicknameAvailabilityResponse.java
  src/main/java/org/chzz/market/domain/user/entity/User.java
  src/main/java/org/chzz/market/domain/user/error/UserErrorCode.java
  src/main/java/org/chzz/market/domain/user/oauth2/CustomFailureHandler.java
  src/main/java/org/chzz/market/domain/user/oauth2/CustomSuccessHandler.java
  src/main/java/org/chzz/market/domain/user/repository/UserRepository.java
  src/main/java/org/chzz/market/domain/user/service/CustomOAuth2UserService.java
  src/main/java/org/chzz/market/domain/user/service/UserService.java
  src/main/resources/application-test.yml
  src/test/java/org/chzz/market/domain/token/service/TokenServiceTest.java
  src/test/java/org/chzz/market/domain/user/oauth2/CustomSuccessHandlerTest.java
  src/test/java/org/chzz/market/domain/user/service/UserServiceTest.java
  src/test/java/org/chzz/market/util/UserTestFactory.java
Labels: ✨feature, 👨🏻‍💻backend, 🗂️db

#27 feat: 경매 종료 기능 구현
  build.gradle
  src/main/java/org/chzz/market/common/config/AutowiringSpringBeanJobFactory.java
  src/main/java/org/chzz/market/common/config/QuartzConfig.java
  src/main/java/org/chzz/market/common/config/SecurityConfig.java
  src/main/java/org/chzz/market/common/config/logging/P6spyLogMessageFormatConfiguration.java
  src/main/java/org/chzz/market/common/quartz/MyJobListener.java
  src/main/java/org/chzz/market/common/quartz/MyTriggerListener.java
  src/main/java/org/chzz/market/domain/auction/entity/Auction.java
  src/main/java/org/chzz/market/domain/auction/entity/listener/AuctionEntityListener.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImpl.java
  src/main/java/org/chzz/market/domain/auction/schedule/AuctionEndJob.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/bid/repository/BidRepositoryCustom.java
  src/main/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/bid/service/BidService.java
  src/main/java/org/chzz/market/domain/notification/dto/NotificationEvent.java
  src/main/java/org/chzz/market/domain/notification/dto/NotificationMessage.java
  src/main/java/org/chzz/market/domain/notification/entity/Notification.java
  src/main/java/org/chzz/market/domain/notification/service/NotificationEventListener.java
  src/main/java/org/chzz/market/domain/notification/service/NotificationService.java
  src/main/java/org/chzz/market/domain/notification/service/RedisSubscriber.java
  src/main/resources/application-test.yml
  src/main/resources/db/quartz-create.sql
  src/test/java/org/chzz/market/common/DatabaseTest.java
  src/test/java/org/chzz/market/common/QuartzConfig.java
  src/test/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/bid/service/BidServiceTest.java
Labels: ✨feature, 👨🏻‍💻backend
