Repository JECT-Study/Chzz-Market-Backend, pull requests merged in 2024-10, with the labels that each got.

#59 refactor: 경매 등록 이미지 처리 방식 수정
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
  src/main/java/org/chzz/market/domain/image/error/ImageErrorCode.java
  src/main/java/org/chzz/market/domain/image/service/ImageService.java
  src/main/java/org/chzz/market/domain/image/service/ImageUploader.java
  src/main/java/org/chzz/market/domain/image/service/S3ImageUploader.java
  src/main/java/org/chzz/market/domain/product/controller/ProductController.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
Labels: 🪄refactor

#61 feat: find registered product auction
  .github/workflows/pr-title-and-branch-validation.yml
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustom.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/product/controller/ProductController.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/org/chzz/market/domain/product/service/ProductService.java
Labels: ✨feature

#60 refactor: fix simple profile
  src/main/java/org/chzz/market/domain/auction/entity/Auction.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustom.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/user/service/UserService.java
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/user/service/UserServiceTest.java
Labels: 🪄refactor

#62 refactor: ErrorResponse 응답 구조 변경
  src/main/java/org/chzz/market/common/error/ErrorResponse.java
  src/main/java/org/chzz/market/common/error/GlobalErrorCode.java
  src/main/java/org/chzz/market/common/error/handler/GlobalExceptionHandler.java
  src/main/java/org/chzz/market/common/error/response/ErrorResponse.java
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/bid/controller/BidController.java
  src/main/java/org/chzz/market/domain/notification/controller/NotificationController.java
Labels: 🪄refactor

#63 release: 0.1.1
  .github/workflows/pr-title-and-branch-validation.yml
  .github/workflows/release-tag.yml
  compose-local.yaml
  nginx.conf
  src/main/java/org/chzz/market/common/error/ErrorResponse.java
  src/main/java/org/chzz/market/common/error/GlobalErrorCode.java
  src/main/java/org/chzz/market/common/error/handler/GlobalExceptionHandler.java
  src/main/java/org/chzz/market/common/error/response/ErrorResponse.java
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
  src/main/java/org/chzz/market/domain/auction/entity/Auction.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustom.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/bid/controller/BidController.java
  src/main/java/org/chzz/market/domain/image/error/ImageErrorCode.java
  src/main/java/org/chzz/market/domain/image/service/ImageService.java
  src/main/java/org/chzz/market/domain/image/service/ImageUploader.java
  src/main/java/org/chzz/market/domain/image/service/S3ImageUploader.java
  src/main/java/org/chzz/market/domain/notification/controller/NotificationController.java
  src/main/java/org/chzz/market/domain/product/controller/ProductController.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/org/chzz/market/domain/product/service/ProductService.java
  src/main/java/org/chzz/market/domain/user/service/UserService.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/user/oauth2/CustomSuccessHandlerTest.java
  src/test/java/org/chzz/market/domain/user/service/UserServiceTest.java
Labels: ✨ patch

#66 refactor: 이미지 CDN 경로 수정
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/image/service/ImageService.java
Labels: 🪄refactor

#65 refactor: 입찰 가능 횟수 변경
  .github/workflows/pr-title-and-branch-validation.yml
  src/main/java/org/chzz/market/domain/bid/entity/Bid.java
  src/main/resources/db/migration/V2__update_default_count_value.sql
  src/main/resources/db/migration/V3__reorder_columns.sql
  src/test/java/org/chzz/market/domain/bid/service/BidServiceTest.java
Labels: 🪄refactor

#67 release: 0.1.1
  .github/workflows/pr-title-and-branch-validation.yml
  .github/workflows/release-tag.yml
  compose-local.yaml
  nginx.conf
  src/main/java/org/chzz/market/common/error/ErrorResponse.java
  src/main/java/org/chzz/market/common/error/GlobalErrorCode.java
  src/main/java/org/chzz/market/common/error/handler/GlobalExceptionHandler.java
  src/main/java/org/chzz/market/common/error/response/ErrorResponse.java
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
  src/main/java/org/chzz/market/domain/auction/entity/Auction.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustom.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/bid/controller/BidController.java
  src/main/java/org/chzz/market/domain/bid/entity/Bid.java
  src/main/java/org/chzz/market/domain/image/error/ImageErrorCode.java
  src/main/java/org/chzz/market/domain/image/service/ImageService.java
  src/main/java/org/chzz/market/domain/image/service/ImageUploader.java
  src/main/java/org/chzz/market/domain/image/service/S3ImageUploader.java
  src/main/java/org/chzz/market/domain/notification/controller/NotificationController.java
  src/main/java/org/chzz/market/domain/product/controller/ProductController.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/org/chzz/market/domain/product/service/ProductService.java
  src/main/java/org/chzz/market/domain/user/service/UserService.java
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V2__update_default_count_value.sql
  src/main/resources/db/migration/V3__reorder_columns.sql
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/bid/service/BidServiceTest.java
  src/test/java/org/chzz/market/domain/user/oauth2/CustomSuccessHandlerTest.java
  src/test/java/org/chzz/market/domain/user/service/UserServiceTest.java
Labels: ✨ patch

#68 refactor: renaming response object
  src/main/java/org/chzz/market/common/error/GlobalErrorCode.java
  src/main/java/org/chzz/market/domain/auction/dto/BaseAuctionDto.java
  src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/AuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/LostAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/SimpleAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/StartAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/UserAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/WonAuctionResponse.java
  src/main/java/org/chzz/market/domain/bid/dto/query/BiddingRecord.java
  src/main/java/org/chzz/market/domain/bid/dto/response/BidInfoResponse.java
  src/main/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/notification/dto/response/NotificationResponse.java
  src/main/java/org/chzz/market/domain/payment/controller/PaymentController.java
  src/main/java/org/chzz/market/domain/product/controller/ProductController.java
  src/main/java/org/chzz/market/domain/product/dto/BaseProductDTO.java
  src/main/java/org/chzz/market/domain/product/dto/BaseProductDto.java
  src/main/java/org/chzz/market/domain/product/dto/ProductDetailsResponse.java
  src/main/java/org/chzz/market/domain/product/dto/ProductResponse.java
  src/main/java/org/chzz/market/domain/product/dto/UpdateProductResponse.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/user/controller/UserController.java
  src/main/java/org/chzz/market/domain/user/dto/response/UserProfileResponse.java
  src/test/java/org/chzz/market/domain/auction/controller/AuctionControllerTest.java
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
  src/test/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java
  src/test/java/org/chzz/market/domain/user/service/UserServiceTest.java
  src/test/java/org/chzz/market/util/UserTestFactory.java
Labels: 🪄refactor

#70 fix: 입찰 이력이 없을 때 입찰 가능 횟수가 0으로 표시되는 문제 수정
  .github/workflows/pr-title-and-branch-validation.yml
  src/main/java/org/chzz/market/common/config/RedisConfig.java
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/auction/type/TestService.java
  src/main/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImpl.java
  src/main/resources/application-test.yml
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImplTest.java
Labels: 🐛bug

#71 fix: 내가 실패한 경매 조회에서 입찰 최고가 수정
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepository.java
  src/main/java/org/chzz/market/domain/product/service/ProductService.java
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java
Labels: 🐛bug

#73 release: 0.1.2
  .github/workflows/pr-title-and-branch-validation.yml
  src/main/java/org/chzz/market/common/config/RedisConfig.java
  src/main/java/org/chzz/market/common/error/GlobalErrorCode.java
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/dto/BaseAuctionDto.java
  src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/AuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/LostAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/SimpleAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/StartAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/UserAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/WonAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/auction/type/TestService.java
  src/main/java/org/chzz/market/domain/bid/dto/BidCreateRequest.java
  src/main/java/org/chzz/market/domain/bid/dto/query/BiddingRecord.java
  src/main/java/org/chzz/market/domain/bid/dto/response/BidInfoResponse.java
  src/main/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/bid/service/BidService.java
  src/main/java/org/chzz/market/domain/notification/dto/response/NotificationResponse.java
  src/main/java/org/chzz/market/domain/payment/controller/PaymentController.java
  src/main/java/org/chzz/market/domain/product/controller/ProductController.java
  src/main/java/org/chzz/market/domain/product/dto/BaseProductDTO.java
  src/main/java/org/chzz/market/domain/product/dto/BaseProductDto.java
  src/main/java/org/chzz/market/domain/product/dto/ProductDetailsResponse.java
  src/main/java/org/chzz/market/domain/product/dto/ProductResponse.java
  src/main/java/org/chzz/market/domain/product/dto/UpdateProductResponse.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepository.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/product/service/ProductService.java
  src/main/java/org/chzz/market/domain/user/controller/UserController.java
  src/main/java/org/chzz/market/domain/user/dto/response/UserProfileResponse.java
  src/main/resources/application-test.yml
  src/test/java/org/chzz/market/domain/auction/controller/AuctionControllerTest.java
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
  src/test/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/bid/service/BidServiceTest.java
  src/test/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java
  src/test/java/org/chzz/market/domain/user/service/UserServiceTest.java
  src/test/java/org/chzz/market/util/UserTestFactory.java
Labels: ✨ patch

#74 refactor: fix register request
  src/main/java/org/chzz/market/domain/product/dto/ProductDetailsResponse.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
  src/test/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImplTest.java
Labels: 🪄refactor

#75 refactor: 사전등록 수정 요청 DTO 일부 필드 이름 수정
  src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
  src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java
Labels: 🪄refactor

#76 fix: 내가 등록한 사전 경매 제품 조회 쿼리 수정
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/user/dto/response/UserProfileResponse.java
Labels: 🐛bug

#77 release: 0.1.3
  src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/product/dto/ProductDetailsResponse.java
  src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/user/dto/response/UserProfileResponse.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
  src/test/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java
Labels: ✨ patch

#79 chore: Pull Request review reminder action 추가
  .github/workflows/pr_review_reminder.yml
Labels: ⚙️chore

#78 feat: 회원 프로필 이미지 기능 구현
  .github/workflows/pr-title-and-branch-validation.yml
  src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/image/service/ImageService.java
  src/main/java/org/chzz/market/domain/product/dto/ProductDetailsResponse.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/user/controller/UserController.java
  src/main/java/org/chzz/market/domain/user/dto/request/UpdateUserProfileRequest.java
  src/main/java/org/chzz/market/domain/user/dto/response/UpdateProfileResponse.java
  src/main/java/org/chzz/market/domain/user/dto/response/UserProfileResponse.java
  src/main/java/org/chzz/market/domain/user/entity/User.java
  src/main/java/org/chzz/market/domain/user/service/UserService.java
  src/main/resources/db/migration/V4__add_profile_image_url_to_users.sql
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
  src/test/java/org/chzz/market/domain/user/service/UserServiceTest.java
Labels: ✨feature

#81 refactor: fix auction history condition
  nginx.conf
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/user/entity/User.java
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
Labels: 🪄refactor

#82 release: 0.2.0
  .github/workflows/pr-title-and-branch-validation.yml
  .github/workflows/pr_review_reminder.yml
  nginx.conf
  src/main/java/org/chzz/market/MarketApplication.java
  src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/image/dto/ImageResponse.java
  src/main/java/org/chzz/market/domain/image/error/ImageErrorCode.java
  src/main/java/org/chzz/market/domain/image/service/ImageService.java
  src/main/java/org/chzz/market/domain/image/service/S3ImageUploader.java
  src/main/java/org/chzz/market/domain/product/dto/ProductDetailsResponse.java
  src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
  src/main/java/org/chzz/market/domain/product/dto/UpdateProductResponse.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/product/service/ProductService.java
  src/main/java/org/chzz/market/domain/user/controller/UserController.java
  src/main/java/org/chzz/market/domain/user/dto/request/UpdateUserProfileRequest.java
  src/main/java/org/chzz/market/domain/user/dto/response/UpdateProfileResponse.java
  src/main/java/org/chzz/market/domain/user/dto/response/UserProfileResponse.java
  src/main/java/org/chzz/market/domain/user/entity/User.java
  src/main/java/org/chzz/market/domain/user/service/UserService.java
  src/main/resources/db/migration/V4__add_profile_image_url_to_users.sql
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
  src/test/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java
  src/test/java/org/chzz/market/domain/user/service/UserServiceTest.java
Labels: ✨ minor

#83 chore: github action skip 상황 추가
  .github/workflows/pr-title-and-branch-validation.yml
  .github/workflows/pr_review_reminder.yml
Labels: ⚙️chore

#84 refactor: fix image upload method
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/auction/service/register/AuctionRegisterService.java
  src/main/java/org/chzz/market/domain/auction/service/register/PreRegisterService.java
  src/main/java/org/chzz/market/domain/image/entity/Image.java
  src/main/java/org/chzz/market/domain/image/error/ImageErrorCode.java
  src/main/java/org/chzz/market/domain/image/repository/ImageRepository.java
  src/main/java/org/chzz/market/domain/image/service/ImageService.java
  src/main/java/org/chzz/market/domain/product/controller/ProductController.java
  src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/java/org/chzz/market/domain/product/error/ProductErrorCode.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/product/service/ProductService.java
  src/main/resources/db/migration/V5__add_image_sequence.sql
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java
Labels: 🪄refactor

#85 fix: 상품 수정시 이미지 등록 버그 수정
  .github/release-drafter-config.yml
  src/main/java/org/chzz/market/domain/auction/service/register/AuctionRegisterService.java
  src/main/java/org/chzz/market/domain/auction/service/register/PreRegisterService.java
  src/main/java/org/chzz/market/domain/image/entity/Image.java
  src/main/java/org/chzz/market/domain/image/repository/ImageRepository.java
  src/main/java/org/chzz/market/domain/image/service/ImageService.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/java/org/chzz/market/domain/product/service/ProductService.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
  src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java
Labels: 🐛bug

#87 fix: 테스트 API 이미지 저장 로직 시퀀스 누락 수정
  src/main/java/org/chzz/market/domain/auction/type/TestService.java
Labels: 🐛bug

#88 fix: 정식 경매 제품을 사전 경매 조회 시 조회되는 버그 수정
  .github/workflows/pr-title-and-branch-validation.yml
  src/main/java/org/chzz/market/domain/payment/service/PaymentService.java
  src/main/java/org/chzz/market/domain/product/error/ProductErrorCode.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/product/service/ProductService.java
  src/main/java/org/chzz/market/domain/user/oauth2/CustomFailureHandler.java
  src/test/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java
Labels: 🐛bug

#86 docs: README 업데이트
  README.md
Labels: 📃docs

#89 release: 0.2.1
  .github/release-drafter-config.yml
  .github/workflows/pr-title-and-branch-validation.yml
  .github/workflows/pr_review_reminder.yml
  README.md
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/auction/service/register/AuctionRegisterService.java
  src/main/java/org/chzz/market/domain/auction/service/register/PreRegisterService.java
  src/main/java/org/chzz/market/domain/auction/type/TestService.java
  src/main/java/org/chzz/market/domain/image/entity/Image.java
  src/main/java/org/chzz/market/domain/image/error/ImageErrorCode.java
  src/main/java/org/chzz/market/domain/image/service/ImageService.java
  src/main/java/org/chzz/market/domain/payment/service/PaymentService.java
  src/main/java/org/chzz/market/domain/product/controller/ProductController.java
  src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/java/org/chzz/market/domain/product/error/ProductErrorCode.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/product/service/ProductService.java
  src/main/java/org/chzz/market/domain/user/oauth2/CustomFailureHandler.java
  src/main/resources/db/migration/V5__add_image_sequence.sql
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
  src/test/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java
Labels: ✨ patch

#92 refactor: 내가 등록한 경매 상태값에 따라 API 분리
  .github/workflows/deployment-config.yml
  .github/workflows/intergration-config.yml
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
  src/main/java/org/chzz/market/domain/auction/dto/response/UserEndedAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustom.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/payment/service/PaymentService.java
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
Labels: 🪄refactor

#96 refactor: 인기순 정렬 조건 수정
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/resources/application-test.yml
  src/main/resources/db/migration/V6__add_index_on_product.sql
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
Labels: 🪄refactor

#93 refactor: 나의 입찰 목록 조회 API 동적쿼리로 수정
  .github/workflows/pr-title-and-branch-validation.yml
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/StartAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustom.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/auction/type/TestService.java
  src/main/java/org/chzz/market/domain/bid/controller/BidController.java
  src/main/java/org/chzz/market/domain/bid/dto/query/BiddingRecord.java
  src/main/java/org/chzz/market/domain/bid/repository/BidRepositoryCustom.java
  src/main/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/bid/service/BidService.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/resources/db/migration/V6__add_index_on_product.sql
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
  src/test/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImplTest.java
Labels: 🪄refactor

#94 fix: SSE 에러처리 버그 수정
  src/main/java/org/chzz/market/common/config/SecurityConfig.java
  src/main/java/org/chzz/market/common/error/GlobalErrorCode.java
  src/main/java/org/chzz/market/common/error/handler/GlobalExceptionHandler.java
  src/main/java/org/chzz/market/domain/notification/controller/NotificationController.java
  src/main/java/org/chzz/market/domain/notification/service/NotificationService.java
Labels: 🐛bug

#97 feat: SSE heartbeat 기능 추가
  nginx.conf
  src/main/java/org/chzz/market/common/config/SchedulingConfig.java
  src/main/java/org/chzz/market/domain/notification/repository/EmitterRepository.java
  src/main/java/org/chzz/market/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/org/chzz/market/domain/notification/service/NotificationService.java
Labels: ✨feature

#95 feat: 배송지 CRUD API 구현
  src/main/java/org/chzz/market/domain/address/controller/AddressController.java
  src/main/java/org/chzz/market/domain/address/dto/DeliveryRequest.java
  src/main/java/org/chzz/market/domain/address/dto/DeliveryResponse.java
  src/main/java/org/chzz/market/domain/address/dto/request/AddressDto.java
  src/main/java/org/chzz/market/domain/address/entity/Address.java
  src/main/java/org/chzz/market/domain/address/error/AddressErrorCode.java
  src/main/java/org/chzz/market/domain/address/error/AddressException.java
  src/main/java/org/chzz/market/domain/address/repository/AddressRepository.java
  src/main/java/org/chzz/market/domain/address/service/AddressService.java
  src/main/resources/db/migration/V6__add_address_columns.sql
  src/test/java/org/chzz/market/domain/address/AddressServiceTest.java
Labels: ✨feature

#101 feat: 결제 점검 및 주문 도메인 추가
  src/main/java/org/chzz/market/domain/address/exception/AddressErrorCode.java
  src/main/java/org/chzz/market/domain/address/exception/AddressException.java
  src/main/java/org/chzz/market/domain/order/entity/Order.java
  src/main/java/org/chzz/market/domain/order/repository/OrderRepository.java
  src/main/java/org/chzz/market/domain/order/service/OrderService.java
  src/main/java/org/chzz/market/domain/payment/dto/DeliveryRequest.java
  src/main/java/org/chzz/market/domain/payment/dto/SuccessfulPaymentEvent.java
  src/main/java/org/chzz/market/domain/payment/dto/request/ApprovalRequest.java
  src/main/java/org/chzz/market/domain/payment/error/PaymentErrorCode.java
  src/main/java/org/chzz/market/domain/payment/repository/PaymentRepository.java
  src/main/java/org/chzz/market/domain/payment/service/PaymentService.java
  src/main/resources/db/migration/V7__add_orders_table.sql
Labels: ✨feature

#99 feat: springdoc-openapi 도입
  build.gradle
  src/main/java/org/chzz/market/common/config/SecurityConfig.java
  src/main/java/org/chzz/market/common/config/SpringDocConfig.java
  src/main/java/org/chzz/market/common/filter/NotFoundFilter.java
  src/main/java/org/chzz/market/common/springdoc/ApiExceptionExplainParser.java
  src/main/java/org/chzz/market/common/springdoc/ApiExceptionExplanation.java
  src/main/java/org/chzz/market/common/springdoc/ApiResponseExplanations.java
  src/main/java/org/chzz/market/domain/address/controller/AddressApi.java
  src/main/java/org/chzz/market/domain/address/controller/AddressController.java
  src/main/java/org/chzz/market/domain/auction/controller/AuctionApi.java
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auction/error/AuctionErrorCode.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/bid/controller/BidApi.java
  src/main/java/org/chzz/market/domain/bid/controller/BidController.java
  src/main/java/org/chzz/market/domain/bid/error/BidErrorCode.java
  src/main/java/org/chzz/market/domain/image/error/ImageErrorCode.java
  src/main/java/org/chzz/market/domain/like/error/LikeErrorCode.java
  src/main/java/org/chzz/market/domain/notification/controller/NotificationApi.java
  src/main/java/org/chzz/market/domain/notification/controller/NotificationController.java
  src/main/java/org/chzz/market/domain/notification/error/NotificationErrorCode.java
  src/main/java/org/chzz/market/domain/payment/controller/PaymentApi.java
  src/main/java/org/chzz/market/domain/payment/controller/PaymentController.java
  src/main/java/org/chzz/market/domain/payment/error/PaymentErrorCode.java
  src/main/java/org/chzz/market/domain/payment/error/TossPaymentErrorCode.java
  src/main/java/org/chzz/market/domain/product/controller/ProductApi.java
  src/main/java/org/chzz/market/domain/product/controller/ProductController.java
  src/main/java/org/chzz/market/domain/product/error/ProductErrorCode.java
  src/main/java/org/chzz/market/domain/token/error/TokenErrorCode.java
  src/main/java/org/chzz/market/domain/user/controller/UserApi.java
  src/main/java/org/chzz/market/domain/user/controller/UserController.java
  src/main/java/org/chzz/market/domain/user/error/UserErrorCode.java
Labels: ✨feature

#102 refactor: 주문 도입 이후 나의 성공한 경매 목록 조회 API 수정
  src/main/java/org/chzz/market/domain/auction/dto/response/UserEndedAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/dto/response/WonAuctionResponse.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/order/service/OrderService.java
  src/main/java/org/chzz/market/domain/payment/dto/DeliveryRequest.java
  src/main/java/org/chzz/market/domain/payment/dto/ShippingAddressRequest.java
  src/main/java/org/chzz/market/domain/payment/dto/SuccessfulPaymentEvent.java
  src/main/java/org/chzz/market/domain/payment/dto/request/ApprovalRequest.java
  src/main/java/org/chzz/market/domain/payment/service/PaymentService.java
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
Labels: 🪄refactor

#103 refactor: 상세정보 조회 API에 주문 및 낙찰 여부 추가
  src/main/java/org/chzz/market/domain/auction/controller/AuctionApi.java
  src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/order/entity/Order.java
  src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
Labels: 🪄refactor

#104 fix: 결제 승인 점검 로직 수정
  src/main/java/org/chzz/market/domain/payment/entity/Payment.java
  src/main/java/org/chzz/market/domain/payment/service/PaymentService.java
  src/test/java/org/chzz/market/domain/payment/service/PaymentServiceTest.java
Labels: 🐛bug

#106 fix: CD github action 버그 수정
  .github/workflows/deployment-config.yml
Labels: 🐛bug

#108 refactor: 테이블 및 컬럼 제거, 베스트 경매 정렬 순서 추가, 검증 조건 추가
  src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/bank_account/entity/BankAccount.java
  src/main/java/org/chzz/market/domain/user/dto/request/UpdateUserProfileRequest.java
  src/main/java/org/chzz/market/domain/user/dto/request/UserCreateRequest.java
  src/main/java/org/chzz/market/domain/user/dto/response/UserProfileResponse.java
  src/main/java/org/chzz/market/domain/user/entity/User.java
  src/main/java/org/chzz/market/domain/user/service/UserService.java
  src/main/resources/db/migration/V8__drop_bank_account.sql
  src/main/resources/db/migration/V9__drop_users_link.sql
  src/test/java/org/chzz/market/domain/user/service/UserServiceTest.java
Labels: 🪄refactor

#109 fix: 상품 수정 요청 필드 수정
  src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
Labels: 🐛bug

#111 refactor: 일부 API 유효성 검사 수정
  src/main/java/org/chzz/market/common/error/handler/GlobalExceptionHandler.java
  src/main/java/org/chzz/market/domain/address/controller/AddressApi.java
  src/main/java/org/chzz/market/domain/address/dto/DeliveryRequest.java
  src/main/java/org/chzz/market/domain/auction/controller/AuctionApi.java
  src/main/java/org/chzz/market/domain/bid/controller/BidApi.java
  src/main/java/org/chzz/market/domain/order/service/OrderService.java
  src/main/java/org/chzz/market/domain/payment/controller/PaymentApi.java
  src/main/java/org/chzz/market/domain/payment/controller/PaymentController.java
  src/main/java/org/chzz/market/domain/product/controller/ProductApi.java
  src/main/java/org/chzz/market/domain/user/controller/UserApi.java
  src/main/java/org/chzz/market/domain/user/controller/UserController.java
Labels: 🪄refactor

#110 release: 1.0.1
  src/main/java/org/chzz/market/common/error/handler/GlobalExceptionHandler.java
  src/main/java/org/chzz/market/domain/address/controller/AddressApi.java
  src/main/java/org/chzz/market/domain/address/dto/DeliveryRequest.java
  src/main/java/org/chzz/market/domain/auction/controller/AuctionApi.java
  src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/bank_account/entity/BankAccount.java
  src/main/java/org/chzz/market/domain/bid/controller/BidApi.java
  src/main/java/org/chzz/market/domain/order/service/OrderService.java
  src/main/java/org/chzz/market/domain/payment/controller/PaymentApi.java
  src/main/java/org/chzz/market/domain/payment/controller/PaymentController.java
  src/main/java/org/chzz/market/domain/product/controller/ProductApi.java
  src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
  src/main/java/org/chzz/market/domain/user/controller/UserApi.java
  src/main/java/org/chzz/market/domain/user/controller/UserController.java
  src/main/java/org/chzz/market/domain/user/dto/request/UpdateUserProfileRequest.java
  src/main/java/org/chzz/market/domain/user/dto/request/UserCreateRequest.java
  src/main/java/org/chzz/market/domain/user/dto/response/UserProfileResponse.java
  src/main/java/org/chzz/market/domain/user/entity/User.java
  src/main/java/org/chzz/market/domain/user/service/UserService.java
  src/main/resources/db/migration/V8__drop_bank_account.sql
  src/main/resources/db/migration/V9__drop_users_link.sql
  src/test/java/org/chzz/market/domain/user/service/UserServiceTest.java
Labels: ✨ patch

#112 fix: jwt 토큰 재발행시 동시성 문제 해결 및 분산락 적용
  .github/workflows/deployment-config.yml
  .github/workflows/intergration-config.yml
  build.gradle
  src/main/java/org/chzz/market/common/aop/redisrock/AopForTransaction.java
  src/main/java/org/chzz/market/common/aop/redisrock/CustomSpringELParser.java
  src/main/java/org/chzz/market/common/aop/redisrock/DistributedLock.java
  src/main/java/org/chzz/market/common/aop/redisrock/DistributedLockAop.java
  src/main/java/org/chzz/market/common/config/AWSConfig.java
  src/main/java/org/chzz/market/common/config/RedisConfig.java
  src/main/java/org/chzz/market/common/config/RedissonConfig.java
  src/main/java/org/chzz/market/common/dto/ApiEndpoint.java
  src/main/java/org/chzz/market/common/error/GlobalErrorCode.java
  src/main/java/org/chzz/market/common/filter/JWTFilter.java
  src/main/java/org/chzz/market/common/util/CookieUtil.java
  src/main/java/org/chzz/market/domain/notification/entity/NotificationType.java
  src/main/java/org/chzz/market/domain/token/service/TokenService.java
  src/main/java/org/chzz/market/domain/user/controller/UserController.java
  src/main/resources/application-test.yml
  src/test/java/org/chzz/market/MarketApplicationTests.java
  src/test/java/org/chzz/market/common/AWSConfig.java
  src/test/java/org/chzz/market/domain/token/service/TokenServiceTest.java
Labels: 🐛bug

#113 refactor: 일부 필드 요청시 줄바꿈 허용으로 수정
  src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
  src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/java/org/chzz/market/domain/user/dto/request/UpdateUserProfileRequest.java
  src/main/java/org/chzz/market/domain/user/dto/request/UserCreateRequest.java
  src/test/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequestTest.java
Labels: 🪄refactor

#114 refactor: 금액 범위 수정
  src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
  src/main/java/org/chzz/market/domain/bid/dto/BidCreateRequest.java
  src/main/java/org/chzz/market/domain/order/service/OrderService.java
  src/main/java/org/chzz/market/domain/payment/dto/SuccessfulPaymentEvent.java
  src/main/java/org/chzz/market/domain/payment/dto/request/ApprovalRequest.java
  src/main/java/org/chzz/market/domain/payment/dto/request/ShippingAddressRequest.java
  src/main/java/org/chzz/market/domain/payment/service/PaymentService.java
  src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
  src/test/java/org/chzz/market/domain/payment/service/PaymentServiceTest.java
Labels: 🪄refactor
