Repository JECT-Study/Chzz-Market-Backend, pull requests merged in 2024-11, with the labels that each got.

#115 feat: 사전 등록 상품 목록 조회에 isSeller 추가
  src/main/java/org/chzz/market/domain/product/dto/ProductResponse.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
Labels: ✨feature

#116 refactor: 일부 테이블 필드 변경
  src/main/java/org/chzz/market/domain/address/dto/DeliveryResponse.java
  src/main/java/org/chzz/market/domain/address/error/AddressException.java
  src/main/java/org/chzz/market/domain/address/exception/AddressErrorCode.java
  src/main/java/org/chzz/market/domain/address/exception/AddressException.java
  src/main/java/org/chzz/market/domain/address/repository/AddressRepository.java
  src/main/java/org/chzz/market/domain/address/service/AddressService.java
  src/main/java/org/chzz/market/domain/auction/entity/Auction.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
  src/main/java/org/chzz/market/domain/bid/dto/BidCreateRequest.java
  src/main/java/org/chzz/market/domain/bid/entity/Bid.java
  src/main/java/org/chzz/market/domain/bid/repository/BidRepository.java
  src/main/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImpl.java
  src/main/java/org/chzz/market/domain/bid/service/BidService.java
  src/main/java/org/chzz/market/domain/delivery/controller/DeliveryApi.java
  src/main/java/org/chzz/market/domain/delivery/controller/DeliveryController.java
  src/main/java/org/chzz/market/domain/delivery/dto/DeliveryRequest.java
  src/main/java/org/chzz/market/domain/delivery/dto/DeliveryResponse.java
  src/main/java/org/chzz/market/domain/delivery/entity/Delivery.java
  src/main/java/org/chzz/market/domain/delivery/error/DeliveryErrorCode.java
  src/main/java/org/chzz/market/domain/delivery/error/DeliveryException.java
  src/main/java/org/chzz/market/domain/delivery/repository/DeliveryRepository.java
  src/main/java/org/chzz/market/domain/delivery/service/DeliveryService.java
  src/main/java/org/chzz/market/domain/notification/entity/AuctionFailureNotification.java
  src/main/java/org/chzz/market/domain/notification/entity/AuctionNonWinnerNotification.java
  src/main/java/org/chzz/market/domain/notification/entity/AuctionStartNotification.java
  src/main/java/org/chzz/market/domain/notification/entity/AuctionSuccessNotification.java
  src/main/java/org/chzz/market/domain/notification/entity/AuctionWinnerNotification.java
  src/main/java/org/chzz/market/domain/notification/entity/Notification.java
  src/main/java/org/chzz/market/domain/notification/entity/NotificationType.java
  src/main/java/org/chzz/market/domain/notification/entity/PreAuctionCanceledNotification.java
  src/main/java/org/chzz/market/domain/notification/event/NotificationEvent.java
  src/main/java/org/chzz/market/domain/notification/event/NotificationEventListener.java
  src/main/java/org/chzz/market/domain/notification/repository/NotificationRepositoryImpl.java
  src/main/java/org/chzz/market/domain/notification/service/NotificationService.java
  src/main/java/org/chzz/market/domain/order/entity/Order.java
  src/main/java/org/chzz/market/domain/order/service/OrderService.java
  src/main/java/org/chzz/market/domain/payment/entity/Payment.java
  src/main/java/org/chzz/market/domain/payment/repository/PaymentRepository.java
  src/main/java/org/chzz/market/domain/payment/service/PaymentService.java
  src/main/java/org/chzz/market/domain/product/entity/Product.java
  src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/resources/db/data.sql
  src/main/resources/db/migration/V10__modify_field_name.sql
  src/main/resources/db/migration/V11__notification_image_path.sql
  src/main/resources/db/migration/V12__modify_bid_field.sql
  src/main/resources/db/migration/V13__delete_notification_user_id_foreign_key.sql
  src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImplTest.java
  src/test/java/org/chzz/market/domain/bid/service/BidServiceTest.java
  src/test/java/org/chzz/market/domain/delivery/DeliveryServiceTest.java
  src/test/java/org/chzz/market/domain/notification/repository/NotificationRepositoryImplTest.java
  src/test/java/org/chzz/market/domain/notification/service/NotificationServiceTest.java
  src/test/java/org/chzz/market/domain/user/service/UserServiceTest.java
Labels: 🪄refactor

#117 feat: 경매 V2 API 구조 생성
  src/main/java/org/chzz/market/common/config/SecurityConfig.java
  src/main/java/org/chzz/market/common/config/SpringDocConfig.java
  src/main/java/org/chzz/market/common/config/WebConfig.java
  src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
  src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionDetailApi.java
  src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionDetailController.java
  src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionV2Api.java
  src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionV2Controller.java
  src/main/java/org/chzz/market/domain/auctionv2/dto/view/AuctionType.java
  src/main/java/org/chzz/market/domain/auctionv2/dto/view/UserAuctionType.java
  src/main/java/org/chzz/market/domain/auctionv2/entity/AuctionV2.java
  src/main/java/org/chzz/market/domain/auctionv2/repository/AuctionV2Repository.java
  src/main/java/org/chzz/market/domain/bid/controller/BidController.java
  src/main/java/org/chzz/market/domain/delivery/controller/DeliveryController.java
  src/main/java/org/chzz/market/domain/notification/controller/NotificationController.java
  src/main/java/org/chzz/market/domain/payment/controller/PaymentController.java
  src/main/java/org/chzz/market/domain/product/controller/ProductController.java
  src/main/java/org/chzz/market/domain/user/controller/UserController.java
  src/main/resources/db/migration/V14__create_v2_auction.sql
Labels: ✨feature

#119 refactor: 경매 삭제 API 전환
  src/main/java/org/chzz/market/common/config/AWSConfig.java
  src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionDetailApi.java
  src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionDetailController.java
  src/main/java/org/chzz/market/domain/auctionv2/entity/AuctionStatus.java
  src/main/java/org/chzz/market/domain/auctionv2/entity/AuctionV2.java
  src/main/java/org/chzz/market/domain/auctionv2/entity/Category.java
  src/main/java/org/chzz/market/domain/auctionv2/error/AuctionErrorCode.java
  src/main/java/org/chzz/market/domain/auctionv2/error/AuctionException.java
  src/main/java/org/chzz/market/domain/auctionv2/service/AuctionDeleteService.java
  src/main/java/org/chzz/market/domain/imagev2/entity/ImageV2.java
  src/main/java/org/chzz/market/domain/imagev2/error/ImageErrorCode.java
  src/main/java/org/chzz/market/domain/imagev2/error/exception/ImageException.java
  src/main/java/org/chzz/market/domain/imagev2/service/ImageDeleteService.java
  src/main/java/org/chzz/market/domain/likev2/entity/LikeV2.java
  src/main/java/org/chzz/market/domain/likev2/repository/LikeV2Repository.java
  src/main/resources/db/migration/V15__create_like_image.sql
  src/test/java/org/chzz/market/domain/auctionv2/service/AuctionDeleteServiceTest.java
  src/test/java/org/chzz/market/domain/imagev2/service/ImageDeleteServiceTest.java
Labels: 🪄refactor

#124 refactor: 입찰 API, 좋아요 API 전환
  .github/workflows/pr_review_reminder.yml
  README.md
  src/main/java/org/chzz/market/common/aop/redisrock/DistributedLockAop.java
  src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionDetailApi.java
  src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionDetailController.java
  src/main/java/org/chzz/market/domain/auctionv2/entity/AuctionV2.java
  src/main/java/org/chzz/market/domain/auctionv2/error/AuctionErrorCode.java
  src/main/java/org/chzz/market/domain/auctionv2/repository/AuctionV2Repository.java
  src/main/java/org/chzz/market/domain/bid/controller/BidApi.java
  src/main/java/org/chzz/market/domain/bid/controller/BidController.java
  src/main/java/org/chzz/market/domain/bid/repository/BidQueryRepository.java
  src/main/java/org/chzz/market/domain/bid/service/BidCancelLockService.java
  src/main/java/org/chzz/market/domain/bid/service/BidCancelService.java
  src/main/java/org/chzz/market/domain/bid/service/BidCreateService.java
  src/main/java/org/chzz/market/domain/bid/service/BidLookupService.java
  src/main/java/org/chzz/market/domain/likev2/repository/LikeV2Repository.java
  src/main/java/org/chzz/market/domain/likev2/service/LikeUpdateService.java
  src/test/java/org/chzz/market/domain/bid/service/BidCancelLockServiceTest.java
  src/test/java/org/chzz/market/domain/bid/service/BidCreateServiceConcurrencyTest.java
  src/test/java/org/chzz/market/domain/likev2/service/LikeUpdateServiceConcurrencyTest.java
Labels: 🪄refactor

#125 refactor: 경매 목록 조회 API 전환
  src/main/java/org/chzz/market/common/config/SecurityConfig.java
  src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionV2Api.java
  src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionV2Controller.java
  src/main/java/org/chzz/market/domain/auctionv2/dto/response/BaseAuctionResponse.java
  src/main/java/org/chzz/market/domain/auctionv2/dto/response/OfficialAuctionResponse.java
  src/main/java/org/chzz/market/domain/auctionv2/dto/response/PreAuctionResponse.java
  src/main/java/org/chzz/market/domain/auctionv2/dto/view/AuctionType.java
  src/main/java/org/chzz/market/domain/auctionv2/dto/view/UserAuctionType.java
  src/main/java/org/chzz/market/domain/auctionv2/repository/AuctionV2QueryRepository.java
  src/main/java/org/chzz/market/domain/auctionv2/service/AuctionLookupService.java
  src/test/java/org/chzz/market/domain/auctionv2/repository/AuctionV2QueryRepositoryTest.java
Labels: 🪄refactor

#127 refactor: 경매 등록
  src/main/java/org/chzz/market/common/util/ApplicationContextProvider.java
  src/main/java/org/chzz/market/common/validation/annotation/NotEmptyMultipartList.java
  src/main/java/org/chzz/market/common/validation/validator/NotEmptyMultipartListValidator.java
  src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionV2Api.java
  src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionV2Controller.java
  src/main/java/org/chzz/market/domain/auctionv2/dto/AuctionRegisterType.java
  src/main/java/org/chzz/market/domain/auctionv2/dto/AuctionRegistrationEvent.java
  src/main/java/org/chzz/market/domain/auctionv2/dto/ImageUploadEvent.java
  src/main/java/org/chzz/market/domain/auctionv2/dto/request/RegisterRequest.java
  src/main/java/org/chzz/market/domain/auctionv2/entity/AuctionV2.java
  src/main/java/org/chzz/market/domain/auctionv2/schedule/AuctionV2EndJob.java
  src/main/java/org/chzz/market/domain/auctionv2/service/AuctionEndService.java
  src/main/java/org/chzz/market/domain/auctionv2/service/AuctionRegistrationService.java
  src/main/java/org/chzz/market/domain/auctionv2/service/AuctionSchedulingService.java
  src/main/java/org/chzz/market/domain/auctionv2/service/AuctionStartService.java
  src/main/java/org/chzz/market/domain/auctionv2/service/PreAuctionRegistrationService.java
  src/main/java/org/chzz/market/domain/auctionv2/service/RegistrationService.java
  src/main/java/org/chzz/market/domain/image/error/ImageErrorCode.java
  src/main/java/org/chzz/market/domain/image/service/S3ImageUploader.java
  src/main/java/org/chzz/market/domain/imagev2/repository/ImageV2Repository.java
  src/main/java/org/chzz/market/domain/imagev2/service/ImageV2Service.java
  src/test/java/org/chzz/market/domain/auctionv2/controller/AuctionV2ControllerTest.java
  src/test/java/org/chzz/market/util/AuthenticatedRequestTest.java
Labels: 🪄refactor

#128 refactor: 등록 및 좋아요한 사전경매목록조회, 마감임박 조회 API 전환
  src/main/java/org/chzz/market/common/error/handler/GlobalExceptionHandler.java
  src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionV2Api.java
  src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionV2Controller.java
  src/main/java/org/chzz/market/domain/auctionv2/error/AuctionErrorCode.java
  src/main/java/org/chzz/market/domain/auctionv2/repository/AuctionV2QueryRepository.java
  src/main/java/org/chzz/market/domain/auctionv2/service/AuctionLookupService.java
  src/main/java/org/chzz/market/domain/auctionv2/service/AuctionMyService.java
  src/main/java/org/chzz/market/domain/auctionv2/service/AuctionRegistrationService.java
  src/main/java/org/chzz/market/domain/auctionv2/service/PreAuctionRegistrationService.java
  src/test/java/org/chzz/market/domain/auctionv2/controller/AuctionV2ControllerTest.java
  src/test/java/org/chzz/market/domain/auctionv2/repository/AuctionV2QueryRepositoryTest.java
  src/test/java/org/chzz/market/domain/auctionv2/service/AuctionLookupServiceTest.java
Labels: 🪄refactor

#129 refactor: 사용자의 경매 조회 API 전환
  src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionV2Api.java
  src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionV2Controller.java
  src/main/java/org/chzz/market/domain/auctionv2/dto/response/EndedAuctionResponse.java
  src/main/java/org/chzz/market/domain/auctionv2/dto/response/LostAuctionResponse.java
  src/main/java/org/chzz/market/domain/auctionv2/dto/response/ProceedingAuctionResponse.java
  src/main/java/org/chzz/market/domain/auctionv2/dto/response/WonAuctionResponse.java
  src/main/java/org/chzz/market/domain/auctionv2/repository/AuctionV2QueryRepository.java
  src/main/java/org/chzz/market/domain/auctionv2/service/AuctionMyService.java
  src/test/java/org/chzz/market/domain/auctionv2/repository/AuctionV2QueryRepositoryTest.java
Labels: 🪄refactor

#132 fix: 누락된 좋아요순 정렬 추가
  src/main/java/org/chzz/market/domain/auction/controller/AuctionApi.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionQueryRepository.java
Labels: 🐛bug

#133 fix: 경매 수정 시 설명 필드 정규식 오타 수정
  src/main/java/org/chzz/market/domain/auction/dto/request/UpdateAuctionRequest.java
Labels: 🐛bug

#134 fix: 경매 종료 스케줄링 의존성 주입 문제 수정
  src/main/java/org/chzz/market/domain/auction/schedule/AuctionEndJob.java
Labels: 🐛bug

#135 feat: 회원 탈퇴 기능 구현
  src/main/java/org/chzz/market/common/config/OAuth2ClientConfig.java
  src/main/java/org/chzz/market/common/config/RestClientConfig.java
  src/main/java/org/chzz/market/common/config/SecurityConfig.java
  src/main/java/org/chzz/market/domain/auction/repository/AuctionQueryRepository.java
  src/main/java/org/chzz/market/domain/oauth2/dto/response/KaKaoResponse.java
  src/main/java/org/chzz/market/domain/oauth2/dto/response/KakaoTokenResponse.java
  src/main/java/org/chzz/market/domain/oauth2/dto/response/KakaoUnlinkResponse.java
  src/main/java/org/chzz/market/domain/oauth2/dto/response/NaverResponse.java
  src/main/java/org/chzz/market/domain/oauth2/dto/response/NaverTokenResponse.java
  src/main/java/org/chzz/market/domain/oauth2/dto/response/NaverUnlinkResponse.java
  src/main/java/org/chzz/market/domain/oauth2/dto/response/OAuth2Response.java
  src/main/java/org/chzz/market/domain/oauth2/repository/Oauth2RefreshTokenRepository.java
  src/main/java/org/chzz/market/domain/oauth2/service/CustomFailureHandler.java
  src/main/java/org/chzz/market/domain/oauth2/service/CustomOAuth2LoginAuthenticationProvider.java
  src/main/java/org/chzz/market/domain/oauth2/service/CustomOAuth2UserService.java
  src/main/java/org/chzz/market/domain/oauth2/service/CustomSuccessHandler.java
  src/main/java/org/chzz/market/domain/oauth2/service/KakaoSocialLoginService.java
  src/main/java/org/chzz/market/domain/oauth2/service/NaverSocialLoginService.java
  src/main/java/org/chzz/market/domain/oauth2/service/SocialLoginEventListener.java
  src/main/java/org/chzz/market/domain/oauth2/service/SocialLoginService.java
  src/main/java/org/chzz/market/domain/oauth2/service/SocialLoginServiceFactory.java
  src/main/java/org/chzz/market/domain/token/service/TokenService.java
  src/main/java/org/chzz/market/domain/user/controller/UserApi.java
  src/main/java/org/chzz/market/domain/user/controller/UserController.java
  src/main/java/org/chzz/market/domain/user/dto/CustomUserDetails.java
  src/main/java/org/chzz/market/domain/user/dto/UserDeletedEvent.java
  src/main/java/org/chzz/market/domain/user/entity/User.java
  src/main/java/org/chzz/market/domain/user/error/UserErrorCode.java
  src/main/java/org/chzz/market/domain/user/service/UserDeleteService.java
  src/main/resources/application-test.yml
  src/main/resources/db/migration/V2__modify_user_field.sql
  src/test/java/org/chzz/market/domain/token/service/TokenServiceTest.java
  src/test/java/org/chzz/market/domain/user/oauth2/CustomSuccessHandlerTest.java
Labels: ✨feature
